"""Define Track A feature metadata: types, units, bounds, and missingness rules."""

TRACK_A_SCHEMA = {
    "RelSpeed": {
        "description": "speed of the ball at release",
        "dtype": float,
        "unit": "mph",
        "hard_bounds": {"lower": 0, "upper": 100},
        "soft_bounds": {"lower": 50, "upper": 77},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "VertRelAngle": {
        "description": "Signed angle in degrees between the release velocity vector projected onto the YZ plane and the fixed Y-axis at ball release",
        "dtype": float,
        "unit": "deg",
        "hard_bounds": {"lower": -4, "upper": 18},
        "soft_bounds": {"lower": -3, "upper": 12},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "HorzRelAngle": {
        "description": "Angle between the ball’s initial projected direction of travel in the horizontal plane and the forward y-direction at release",
        "dtype": float,
        "unit": "deg",
        "hard_bounds": {"lower": -9, "upper": 6},
        "soft_bounds": {"lower": -4.52, "upper": 4.20},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "SpinRate": {
        "description": "Angular speed of the pitched ball, measured in revolutions per minute (rpm), treated as an initial release-time pitch characteristic",
        "dtype": float,
        "unit": "rpm",
        "hard_bounds": {"lower": 0, "upper": 4000},
        "soft_bounds": {"lower": 440, "upper": 2290},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "SpinAxis": {
        "description": "Orientation of the ball’s spin axis in the tracking system’s reference frame, reported in degrees",
        "dtype": float,
        "unit": "deg",
        "hard_bounds": {"lower": 0, "upper": 360},
        "missingness_rule": {"max_missing_ratio": 0.05},
        "special_handling": "Soft bounds omitted because SpinAxis is circular, not linear",
    },
    "RelHeight": {
        "description": "Vertical height of the ball at the instant of release, expressed in the tracking system referenced to home plate",
        "dtype": float,
        "unit": "m",
        "hard_bounds": {"lower": 0, "upper": 3},
        "soft_bounds": {"lower": 0.95, "upper": 2.24},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "RelSide": {
        "description": "Signed lateral distance of the ball from the tracking system’s y-axis at the instant of release",
        "dtype": float,
        "unit": "m",
        "hard_bounds": {"lower": -2.5, "upper": 2.5},
        "soft_bounds": {"lower": -1.74, "upper": 2.35},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "Extension": {
        "description": "Forward release distance from the pitching rubber toward home plate, measured at the instant of ball release",
        "dtype": float,
        "unit": "ft",
        "hard_bounds": {"lower": 0, "upper": 8},
        "soft_bounds": {"lower": 2.78, "upper": 7.34},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "VertBreak": {
        "description": "Signed vertical displacement at the front-of-home-plate plane between the actual pitch location and the no-gravity straight-line reference from release",
        "dtype": float,
        "unit": "cm",
        "hard_bounds": {"lower": -100, "upper": 0},
        "soft_bounds": {"lower": -62.72, "upper": -2.60},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "InducedVertBreak": {
        "description": "Signed vertical difference at the front-of-home-plate plane between the actual pitch trajectory and a gravity-only reference trajectory from the same release state",
        "dtype": float,
        "unit": "cm",
        "hard_bounds": {"lower": -25, "upper": 25},
        "soft_bounds": {"lower": -23.36, "upper": 23.59},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "HorzBreak": {
        "description": "Signed horizontal difference at the front-of-home-plate plane between the actual pitch crossing location and the no-gravity reference crossing location from the same release state",
        "dtype": float,
        "unit": "cm",
        "hard_bounds": {"lower": -25, "upper": 25},
        "soft_bounds": {"lower": -12.09, "upper": 10.51},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "PlateLocHeight": {
        "description": "Height of the actual pitch at the front-of-home-plate plane, measured relative to home plate",
        "dtype": float,
        "unit": "ft",
        "hard_bounds": {"lower": 0, "upper": 10},
        "soft_bounds": {"lower": 0, "upper": 4.60},
        "missingness_rule": {"max_missing_ratio": 0.05},
        "special_handling": "Raw Tukey lower bound was slightly negative, but because PlateLocHeight has a physical lower limit of 0 ft, the operational soft lower bound was clamped to 0",
    },
    "PlateLocSide": {
        "description": "Signed lateral offset at the front-of-home-plate plane from the fixed center line (x = 0) in the field coordinate system",
        "dtype": float,
        "unit": "ft",
        "hard_bounds": {"lower": -8, "upper": 8},
        "soft_bounds": {"lower": -2.66, "upper": 2.95},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "ZoneSpeed": {
        "description": "Speed of the ball at the instant it crosses the front-of-home-plate plane",
        "dtype": float,
        "unit": "mph",
        "hard_bounds": {"lower": 30, "upper": 80},
        "soft_bounds": {"lower": 46.30, "upper": 71.52},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "VertApprAngle": {
        "description": "Angle between the ball’s projected direction of travel in the vertical plane and the forward y-direction at the front-of-home-plate plane",
        "dtype": float,
        "unit": "deg",
        "soft_bounds": {"lower": -10.03, "upper": 2.67},
        "hard_bounds": {"lower": -15, "upper": 5},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "HorzApprAngle": {
        "description": "Angle between the ball’s projected direction of travel in the horizontal plane and the forward y-direction at the front-of-home-plate plane",
        "dtype": float,
        "unit": "deg",
        "soft_bounds": {"lower": -5.91, "upper": 5.08},
        "hard_bounds": {"lower": -10, "upper": 8},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
    "ZoneTime": {
        "description": "Elapsed time from pitch release to the ball crossing the front-of-home-plate plane",
        "dtype": float,
        "unit": "s",
        "soft_bounds": {"lower": 0.31, "upper": 0.51},
        "hard_bounds": {"lower": 0.2, "upper": 0.8},
        "missingness_rule": {"max_missing_ratio": 0.05},
    },
}

TRACK_A_COLS = list(TRACK_A_SCHEMA)
